server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /browser-extension {
        alias   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /browser-extension/index.html;
    }

    # Redirect root to the subpath (optional, depending on requirements)
    # location = / {
    #     return 301 /browser-extension;
    # }
}
